[target.x86_64-pc-windows-msvc]
# Increase default stack size to avoid running out of stack
# space in debug builds. The size matches Linux's default.
rustflags = [
    "-C", "link-arg=/STACK:8000000"
]
[target.aarch64-pc-windows-msvc]
# Increase default stack size to avoid running out of stack
# space in debug builds. The size matches Linux's default.
rustflags = [
    "-C", "link-arg=/STACK:8000000"
]

[target.riscv32imc-unknown-none-elf]
runner = "espflash flash --monitor --chip esp32c3 --log-format defmt"
rustflags = [
  # Required to obtain backtraces (e.g. when using the "esp-backtrace" crate.)
  # NOTE: May negatively impact performance of produced code
  "-C", "force-frame-pointers",
]

[env]
DEFMT_LOG="info"


[unstable]
build-std = ["alloc", "core"]
